myapp/feedback/urls.py
from django.urls import path
from . import views

app_name='feedback'
urlpatterns = [
	path('', views.index, name='index'),
	path('requestfeedback/<feedback_id>', views.requestFeedback, name='requestFeedback'),
	path('submit/<feedback_id>', views.submit, name='submit'),
]

myapp/myapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('feedback/', include('feedback.urls')),
]

myapp/feedback/models.py
from django.db import models
from django.utils import timezone

class Feedback(models.Model):
	id = models.IntegerField(primary_key=True)
	stars = models.IntegerField(null=True)
	email = models.EmailField()
	comments = models.TextField(null=True, blank=True)
	created_date = models.DateTimeField(default = timezone.now)
	updated_date = models.DateTimeField(default = timezone.now, null=True)
	
	def __str__(self):
		return self.email
	

myapp/feedback/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from . models import Feedback
from django.urls import reverse

def index(request):
	return HttpResponse("Default landing page for feedback");

def requestFeedback(request, feedback_id):
	feedback = get_object_or_404(Feedback, pk=feedback_id)
	return render(request, 'feedback/showFeedback.html', {'feedback':feedback})

def submit(request, feedback_id):
	feedback = get_object_or_404(Feedback, pk=feedback_id)
	try: 
		feedback.stars = request.POST.get('noOfStars')
		feedback.comments = request.POST.get('commenttextarea')
		feedback.save()
		print(feedback.stars)
		print(feedback.comments)
		return HttpResponse('Successfully submitted')
	except(KeyError, Feedback.DoesNotExist):
		return HttpResponse('Error')

myapp/feedback/templates/feedback/showFeedback.html
<html>
<head><h1>Feedback page</h1></head>
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
<style>
div.stars {
  width: 270px;
  display: inline-block;
}

input.star { display: none; }

label.star {
  float: right;
  padding: 10px;
  font-size: 36px;
  color: #444;
  transition: all .2s;
}

input.star:checked ~ label.star:before {
  content: '\f005';
  color: #FD4;
  transition: all .25s;
}

input.star-5:checked ~ label.star:before {
  color: #FE7;
  text-shadow: 0 0 20px #952;
}

input.star-1:checked ~ label.star:before { color: #F62; }

label.star:hover { transform: rotate(-15deg) scale(1.3); }

label.star:before {
  content: '\f006';
  font-family: FontAwesome;
}
</style>
<script>
function verify() {
	
	if((':radio:checked').length > 0) {
		var radio = document.querySelector('input[name="star"]:checked').id;
	    var stars = (radio.substring(5,6));
		document.getElementById("starsVar").value = stars;
		if(stars <= 3) {
			document.getElementById('feedbackcommentdiv').style.visibility = "visible"
		} else {
		document.getElementById('feedbackcommentdiv').style.visibility = "hidden"
		}
	} else {
	  alert("please provide atleast one feedback");
	}
}
</script>
<br>
<body style="margin: auto; width: 50% ; border: 3px; padding: 10px;">
 <form action="{% url 'feedback:submit' feedback.id %}" method="post">
	<div class="stars">
 
  {% csrf_token %}
    <input class="star star-5" id="star-5" type="radio" name="star" onchange="verify()"/>
    <label class="star star-5" for="star-5"></label>
    <input class="star star-4" id="star-4" type="radio" name="star" onchange="verify()"/>
    <label class="star star-4" for="star-4"></label>
    <input class="star star-3" id="star-3" type="radio" name="star" onchange="verify()"/>
    <label class="star star-3" for="star-3"></label>
    <input class="star star-2" id="star-2" type="radio" name="star" onchange="verify()"/>
    <label class="star star-2" for="star-2"></label>
    <input class="star star-1" id="star-1" type="radio" name="star" onchange="verify()"/>
    <label class="star star-1" for="star-1"></label>
	<input type="hidden" id="starsVar" name="noOfStars" value="{{feedback.stars}}"/>
	<div id="feedbackcommentdiv" style="visibility:hidden">
	<output> Please provide feedback to help us improve our service </output>
	<textarea id="feedbackcomment" name="commenttextarea" value="{{feedback.comments}}"></textarea>
	</div>
	</div>
	<br>
<input type="submit" name="Submit"></input>
</div>
</form>
<div>
</body>

myapp/feedback/templates/feedback/success.html
<html>
<h1> Feedback successfully submitted for {{feedback.id}} </h1>